---
# tasks file for roles/apache
- name: Εγκατάσταση Apache webserver
  apt:
    pkg:
      - apache2
      - libapache2-mod-php

- name: Ενεργοποιήση Apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  loop: "{{ apache_modules }}"
  notify:
    - Restart apache2

