---
# tasks file for roles/php
- name: Εγκατάσταση php
  apt:
    pkg:
      - php-fpm
      - php-cgi 
      - php 
      - php-pgsql 
      - php-mbstring 
      - php-intl 
      - php-redis 
      - php-imagick 
      - php-igbinary 
      - php-gmp 
      - php-bcmath 
      - php-curl 
      - php-gd 
      - php-zip 
      - php-imap 
      - php-ldap 
      - php-bz2 
      - php-ssh2 
      - php-phpseclib 
      - php-dev 
      - libsmbclient-dev 
      - php-pear 
    update_cache: yes
    cache_valid_time: 3600  
