---
# tasks file for roles/postgres
- name: Εγκατάσταση βάσης PostgreSQL
  apt:
    pkg:
      - postgresql-13
      - python3-psycopg2
      - acl
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Ορίζουμε την διεργασία της PosrgreSQL να ακούει σε όλες τις IP του host
  lineinfile:
    path: /etc/postgresql/13/main/postgresql.conf
    line: "listen_addresses = '*'"
    insertbefore: '^#listen_addresses'
    firstmatch: yes
  notify:
    - Restart postgresql

- name: Επιτρέπουμε να συνδεόνται όλοι οι χρήστες της βάσης από το τοπικό δικτυο με md5 κωδικο
  lineinfile:
    path: /etc/postgresql/13/main/pg_hba.conf
    line: "host    all             all             {{ ansible_facts.default_ipv4.network }}/24            md5"
    insertafter: '^# IPv4 local connections:'
    firstmatch: yes
  notify:
    - Restart postgresql

- name: Δημιουργούμε χρήστη στη βαση
  postgresql_user:
    name: "{{ dbuser }}"
    password:  "{{ dbpass }}"
  become: yes
  become_user: postgres

- name: Δημιουργούμε βάση και ορίζουμε ιδιοκτήτη της βάσης
  postgresql_db:
    name: "{{ dbname }}"
    owner: "{{ dbuser }}"
  become: yes
  become_user: postgres
